frase = ('  Tossiu Passa boyzão'  )
print(frase[::3])
tamanho = len(frase)
print(frase)
print(frase.count('y'))
oi =('     oi                            krl   ')
print(len(frase.strip()))
print(frase.replace('boyzão','girzona'))
print('boyzão' in frase)
print(frase.find('Passa'))
div = frase.split()
print(div [1] [2])